name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Daniel97Lim/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.helloworldcloudproject }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AKIA4ICA6I77EY2TV6PY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.axEJg8dYgxIeaHjR+3ShsWWpd6hTX6AaK4k8/iD4 }}